### ISSUE TITLE
Writing to the custom digit

### ISSUE THREAD

**Issue by mikeboich** [connornishijima/Lixie_II#2]
I couldn't see how to display the 11th digit (decimal point).  (I realize that write_float does it, but I wanted to do it for purposes other than writing a float value to the display.)  

The write_digit routine has a range check for the number argument (line 284: If(num<10)).

If that test is changed to: if(num<10 || num==255), then the write_digit routine can be used light up the decimal point.

I'm a little bit of a Git novice, and not sure how you handle source code changes for this library, so I'm just posting them as comments here.  Let me know if you prefer something different!

**Comment by connornishijima** [comment]
Sorry for the late reply Mike! This issue has been resolved in Lixie_II ver. 1.3.1 as detailed in the release log:

[https://github.com/connornishijima/Lixie_II/releases/tag/1.3.1](https://github.com/connornishijima/Lixie_II/releases/tag/1.3.1)

> Each Lixie II contains a special 11th pane, that is a decimal point by default but can be replaced by the user with any custom engravings on whatever 3mm materials they'd like.

> Now, users can implicitly or explicitly control these "special panes" using easy functions detailed in the new "special_panes" example included with the Lixie_II library!
