### ISSUE TITLE
You are not connected to http://192.168.4.1

### ISSUE THREAD

**Issue by ememem13** [connornishijima/Lixie_II#5]
Contents of serial monitor:

Failed to read file, using default configuration
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 1
Entered config mode
192.168.4.1
LIXIE CONFIG
*WM: 
*WM: Configuring access point... 
*WM: LIXIE CONFIG
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started

**Comment by connornishijima** [comment]
I'm going to need a little more clarification...

The Serial Monitor output you posted is normal, it means that no WiFi credentials are currently saved and it has opened its own WiFi network called "LIXIE CONFIG" that you can connect your phone to and send it your WiFi info directly by accessing http://192.168.4.1/ in your phone's browser, as detailed in the instructions in the header of WIFI_NTP_CLOCK.ino.

Is that system not working? :(

**Comment by ememem13** [comment]
I can't open http://192.168.4.1/.

**Comment by connornishijima** [comment]
Are you connected to the "LIXIE CONFIG" network?

**Comment by ememem13** [comment]
I do not know.
Where can I do this?

**Comment by connornishijima** [comment]
Are you using a smartphone? In your WiFi settings there should now be network called "LIXIE CONFIG" that you can click on to connect to, similar to how you'd connect your phone to your personal WiFi network. (This temporary network has no password) This network will only be active for about 5 minutes after the clock boots, for security reasons.

On iPhone this is under Settings > WiFi, on Android this is under Settings > Connections > WiFi.

Once connected to this network, (your phone may warn that "Internet is not available" - this is normal) you will be able to pull up http://192.168.4.1/ in your browser.

It will bring up an interface where you can select from a list of nearby WiFi networks that your clock has picked up, and can input your WiFi password settings there. Once entered, the clock will reboot, your phone will reconnect to your usual network, and your Lixie clock will now be able to use your local WiFi to pull accurate NTP time. :)

**Comment by ememem13** [comment]
Thanks!
This was missing from the description.

**Comment by connornishijima** [comment]
No problem, I'll see what I can do to clarify further. :) I'll keep this issue open for now if you have any further questions.
